### ISSUE TITLE
デザイン案

### ISSUE THREAD

**Issue by sakusaku3939** [Neko-Sato/yamabuki-qr#3]
Adobe XDで作ったプロトタイプ
ボタン周りはもう少しこだわる予定

問題無さそうならコードも書き始める（何かしら返事求）

![1](https://user-images.githubusercontent.com/53967490/157543109-10e93e3d-9957-4a65-b456-9d8a94afb8be.jpg)
![2](https://user-images.githubusercontent.com/53967490/157543114-8abc5943-1108-4a50-8a32-ba5d5dbee51c.jpg)

**Comment by Neko-Sato** [comment]
今のよりQRコードを読み込む画面へ行くボタンが分かりやすくて良いと思う。問題なし。

**Comment by sakusaku3939** [comment]
@Neko-Sato 作るタイミングが被ってしまってたことに今気づいた
まだ完成してないからこっちのデザインは没にする

また何かあったらissues開いといて～

![yamabuki-qr2 - Google Chrome 2022_03_13 6_14_26](https://user-images.githubusercontent.com/53967490/158035220-bc258379-89b5-41bf-b830-7969f985699b.png)
